language: java
before_install:
- chmod +x gradlew
jobs:
  include:
  - stage: "Initial Assemble"
    language: java
    script:
    - ./gradlew assemble
  - stage: "Tests"
    language: java
    script:
    - ./gradlew check
    - ./gradlew codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)