name: Build images for Bash automation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-clone-repos:

    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository
        uses: actions/checkout@v2

      - name: Build clone-repos image
        run: |
          cd ./bash/clone-repos && \
          ./build.sh

      - name: Login into the Docker Repository
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/clone-repos:latest
          docker tag clone-repos "$IMAGE_ID"
          docker push "$IMAGE_ID"