name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build with Gradle
        run: ./gradlew build

      - name: Save the Javalin-Start artifact
        uses: actions/upload-artifact@v1
        with:
          name: javalin-artifact
          path: ./javalin/javalin-start/build/libs

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code back, it contains the Dockerfile
        uses: actions/checkout@v2

      - name: Restore Javalin-Start artifact from storage
        uses: actions/download-artifact@v1
        with:
          name: javalin-artifact

      - name: Place the artifact back to the libs folder
        shell: bash
        run: |
          mkdir -p ./javalin/javalin-start/build/libs
          mv ./javalin-artifact/*.jar ./javalin/javalin-start/build/libs

      - name: Build a Docker Image
        run: docker build ./javalin/javalin-start/ --file ./javalin/javalin-start/Dockerfile --tag image